# Generated by Django 2.2.4 on 2019-08-12 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("mozimages", "0001_initial"), ("content", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mozimages.MozImage",
            ),
        )
    ]
