# Generated by Django 2.2.4 on 2019-09-30 09:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20190813_1503'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contentpage',
            managers=[
                ('published_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
