# Generated by Django 2.2.12 on 2020-05-07 13:57
"""Copy any image set as `ContentPage.hero_image` to populate the
`ContentPage.card_image` field instead, including updating the latest
revision of the page (draft or live)"""

from django.db import migrations

from developerportal.apps.common.migration_utils import (
    move_Page_image_to_Page_card_image,
)


def forwards(apps, schema_editor):
    PageSubclass = apps.get_model("content", "ContentPage")
    move_Page_image_to_Page_card_image(PageSubclass, source_field="hero_image")


class Migration(migrations.Migration):

    dependencies = [("content", "0009_contentpage_sidebar")]

    operations = [migrations.RunPython(forwards, migrations.RunPython.noop)]
