# Generated by Django 2.2.14 on 2020-07-15 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mozimages', '0001_initial'),
        ('content', '0013_make_sidebar_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='card_image_3_2',
            field=models.ForeignKey(blank=True, help_text='An image in 3:2 aspect ratio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mozimages.MozImage', verbose_name='Image'),
        ),
    ]
