# Generated by Django 2.2.3 on 2019-07-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("home", "0009_auto_20190702_0904")]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="button_url",
            field=models.URLField(blank=True, default="", max_length=2048),
        )
    ]
