# Generated by Django 2.2.3 on 2019-07-05 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("home", "0010_auto_20190704_1031")]

    operations = [
        migrations.AlterField(
            model_name="homepagefeaturedarticle",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailcore.Page",
            ),
        )
    ]
