# Generated by Django 2.2.1 on 2019-06-28 14:37

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190628_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='featured',
            field=wagtail.core.fields.StreamField([('article', wagtail.core.blocks.PageChooserBlock(page_type=['articles.Article'], required=False)), ('external_page', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock()), ('title', wagtail.core.blocks.CharBlock()), ('intro', wagtail.core.blocks.TextBlock(required=False)), ('header_image', wagtail.images.blocks.ImageChooserBlock(label='Image'))], help_text='Details of an external page'))], blank=True, null=True),
        ),
    ]
