# Generated by Django 2.2.1 on 2019-07-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20190628_1438'),
        ('home', '0009_auto_20190702_0904'),
    ]

    operations = [
    ]
