# Generated by Django 2.2.3 on 2019-07-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_merge_20190702_1247"),
        ("home", "0011_auto_20190705_1258"),
    ]

    operations = []
