# Generated by Django 2.2.3 on 2019-07-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20190710_1751'),
        ('home', '0020_auto_20190708_1243'),
    ]

    operations = [
    ]
