# Generated by Django 2.2.3 on 2019-07-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("home", "0022_auto_20190711_1951")]

    operations = [
        migrations.RemoveField(model_name="homepage", name="description"),
        migrations.AddField(
            model_name="homepage",
            name="about_button_text",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_button_url",
            field=models.URLField(blank=True, default="", max_length=140),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_subtitle",
            field=models.TextField(blank=True, default="", max_length=250),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_title",
            field=models.TextField(blank=True, default="", max_length=250),
        ),
    ]
