# Generated by Django 2.2.4 on 2019-08-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20190813_1425'),
        ('home', '0026_auto_20190813_1302'),
    ]

    operations = [
    ]
