# Generated by Django 2.2.4 on 2019-09-30 09:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20190814_1600'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='homepage',
            managers=[
                ('published_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
