# Generated by Django 2.2.6 on 2019-10-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_homepage_featured_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_header',
            field=models.BooleanField(default=True),
        ),
    ]
