# Generated by Django 2.2.11 on 2020-03-25 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_support_featuring_video_in_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='external_promos',
        ),
    ]
