# Generated by Django 2.2.14 on 2020-07-15 10:03

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_remove_homepage_show_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='featured',
            field=wagtail.core.fields.StreamField([('post', wagtail.core.blocks.PageChooserBlock(page_type=['articles.Article', 'externalcontent.ExternalArticle'])), ('content_page', wagtail.core.blocks.PageChooserBlock(page_type=['content.ContentPage'])), ('external_page', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock()), ('title', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.TextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='16:9 aspect-ratio image', label='16:9 image')), ('image_3_2', wagtail.images.blocks.ImageChooserBlock(help_text='3:2 aspect-ratio image - optiopnal but recommended', label='3:2 image', required=False))])), ('video', wagtail.core.blocks.PageChooserBlock(page_type=['videos.Video']))], blank=True, help_text='Optional space for featured posts, videos or links, min. 2, max. 5. Note that External Video is NOT allowed here.', null=True),
        ),
    ]
