# Generated by Django 2.2.3 on 2019-07-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("externalcontent", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="externalcontent", old_name="url", new_name="external_url"
        )
    ]
