# Generated by Django 2.2.3 on 2019-07-05 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontent', '0002_auto_20190704_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalArticle',
            fields=[
                ('externalcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='externalcontent.ExternalContent')),
            ],
            options={
                'abstract': False,
            },
            bases=('externalcontent.externalcontent',),
        ),
        migrations.CreateModel(
            name='ExternalEvent',
            fields=[
                ('externalcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='externalcontent.ExternalContent')),
            ],
            options={
                'abstract': False,
            },
            bases=('externalcontent.externalcontent',),
        ),
        migrations.CreateModel(
            name='ExternalVideo',
            fields=[
                ('externalcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='externalcontent.ExternalContent')),
            ],
            options={
                'abstract': False,
            },
            bases=('externalcontent.externalcontent',),
        ),
    ]
