# Generated by Django 2.2.3 on 2019-07-09 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mozimages', '0001_initial'),
        ('externalcontent', '0004_auto_20190705_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalarticle',
            old_name='readtime',
            new_name='read_time',
        ),
        migrations.AddField(
            model_name='externalcontent',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mozimages.MozImage'),
        ),
    ]
