# Generated by Django 2.2.3 on 2019-07-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontent', '0007_auto_20190711_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcontent',
            name='description',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
    ]
