# Generated by Django 2.2.3 on 2019-07-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontent', '0011_auto_20190723_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalcontent',
            options={'verbose_name_plural': 'External Content'},
        ),
    ]
