# Generated by Django 2.2.3 on 2019-07-31 12:26

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontent', '0015_auto_20190725_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalarticle',
            name='authors',
            field=wagtail.core.fields.StreamField([('author', wagtail.core.blocks.PageChooserBlock(page_type=['people.Person'])), ('external_author', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Name')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('url', wagtail.core.blocks.URLBlock(label='URL', required=False))]))], blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ExternalArticleAuthor',
        ),
    ]
