# Generated by Django 2.2.4 on 2019-08-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontent', '0019_auto_20190813_1302'),
        ('externalcontent', '0019_auto_20190813_1425'),
    ]

    operations = [
    ]
