# Generated by Django 2.2.4 on 2019-09-25 13:38

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontent', '0022_auto_20190819_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalevent',
            name='location',
        ),
        migrations.RemoveField(
            model_name='externalevent',
            name='venue',
        ),
        migrations.AddField(
            model_name='externalevent',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='externalevent',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2),
        ),
    ]
