# Generated by Django 2.2.4 on 2019-09-30 09:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontent', '0023_auto_20190925_1338'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='externalarticle',
            managers=[
                ('published_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='externalcontent',
            managers=[
                ('published_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='externalevent',
            managers=[
                ('published_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='externalvideo',
            managers=[
                ('published_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
