# Generated by Django 2.2.6 on 2019-11-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontent', '0026_external_person_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalarticle',
            options={'verbose_name': 'External Post', 'verbose_name_plural': 'External Posts'},
        ),
    ]
