# Generated by Django 2.2.6 on 2019-11-01 13:29

import datetime
from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontent', '0027_relabel_external_article_as_external_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalarticle',
            name='authors',
            field=wagtail.core.fields.StreamField([('author', wagtail.core.blocks.PageChooserBlock(page_type=['people.Person'])), ('external_author', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Name')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.CharBlock(label='About', required=False)), ('url', wagtail.core.blocks.URLBlock(label='URL', required=False))]))], blank=True, help_text="Optional list of the external post's authors. Use ‘External author’ to add guest authors without creating a profile on the system", null=True),
        ),
        migrations.AlterField(
            model_name='externalarticle',
            name='date',
            field=models.DateField(default=datetime.date.today, help_text='The date the external post was published', verbose_name='External Post date'),
        ),
        migrations.AlterField(
            model_name='externalarticle',
            name='read_time',
            field=models.CharField(blank=True, help_text='Optional, approximate read-time for this external post, e.g. “2 mins”. This is shown as a small hint when the external post is displayed as a card.', max_length=30),
        ),
    ]
