# Generated by Django 2.2.12 on 2020-05-07 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("externalcontent", "0028_rephrase_articles_as_posts")]

    operations = [
        migrations.RenameField(
            model_name="externalcontent", old_name="image", new_name="card_image"
        )
    ]
