# Generated by Django 2.2.9 on 2020-01-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("externalcontent", "0028_rephrase_articles_as_posts")]

    operations = [
        migrations.AlterModelManagers(name="externalarticle", managers=[]),
        migrations.AlterModelManagers(name="externalcontent", managers=[]),
        migrations.AlterModelManagers(name="externalevent", managers=[]),
        migrations.AlterModelManagers(name="externalvideo", managers=[]),
    ]
