# Generated by Django 2.2.3 on 2019-07-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0002_auto_20190704_1334")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
