# Generated by Django 2.2.3 on 2019-07-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190709_0928'),
        ('events', '0003_auto_20190710_1751'),
    ]

    operations = [
    ]
