# Generated by Django 2.2.3 on 2019-07-11 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190708_1100'),
        ('events', '0004_merge_20190711_1925'),
        ('events', '0004_auto_20190711_1501'),
    ]

    operations = [
    ]
