# Generated by Django 2.2.3 on 2019-07-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190712_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='card_venue',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.TextField(blank=True, default='', help_text='Full address of the event venue, displayed on the event detail page', max_length=250),
        ),
    ]
