# Generated by Django 2.2.3 on 2019-07-18 15:51

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20190716_1346'),
    ]

    operations = [
    ]
