# Generated by Django 2.2.3 on 2019-07-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190717_1258'),
        ('events', '0008_auto_20190716_1346'),
    ]

    operations = [
    ]
