# Generated by Django 2.2.4 on 2019-08-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20190813_1302'),
        ('events', '0014_auto_20190813_1425'),
    ]

    operations = [
    ]
