# Generated by Django 2.2.11 on 2020-03-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_events_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_content',
            field=models.URLField(blank=True, default='', help_text='Link to a page (in this site or elsewhere) with content about this event.', verbose_name='Event content'),
        ),
        migrations.AddField(
            model_name='event',
            name='official_website',
            field=models.URLField(blank=True, default='', verbose_name='Official website'),
        ),
    ]
