# Generated by Django 2.2.13 on 2020-06-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0027_add_Events_top_content_and_bottom_content")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_mozilla_supported_event",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Is this event supported by Mozilla?",
            ),
        )
    ]
