# Generated by Django 2.2.14 on 2020-07-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_event_is_mozilla_supported_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_support_description',
            field=models.CharField(blank=True, help_text="Custom text for the label used to mark how this event was supported by Mozilla. Optional. If absent 'Sponsored by Mozilla' will be used", max_length=64),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_mozilla_supported_event',
            field=models.BooleanField(blank=True, default=False, help_text="Show a label with this event noting Mozilla support for it. Customise the content via 'Event Support Description', below", verbose_name='Is this event supported by Mozilla?'),
        ),
    ]
