FROM node:12.2-alpine AS static

WORKDIR /app/

COPY package.json package-lock.json /app/
RUN npm ci
RUN rm -rf dist

COPY .eslintignore webpack.config.js /app/
COPY src/ /app/src/

CMD npm run build
