# Generated by Django 2.2.1 on 2019-05-17 10:38

import developerportal.apps.common.fields
from django.db import migrations
import wagtail.core.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [("articles", "0002_article_body")]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="body",
            field=developerportal.apps.common.fields.CustomStreamField(
                [
                    (
                        "paragraph",
                        wagtail.core.blocks.RichTextBlock(
                            features=(
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "blockquote",
                                "code",
                                "hr",
                            )
                        ),
                    ),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                ],
                default=None,
            ),
        )
    ]
