# Generated by Django 2.2.1 on 2019-05-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("articles", "0004_auto_20190516_0907")]

    operations = [
        migrations.RemoveField(model_name="article", name="date"),
        migrations.RemoveField(model_name="article", name="intro"),
    ]
