# Generated by Django 2.2.1 on 2019-05-17 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_auto_20190516_1303"),
        ("articles", "0003_auto_20190517_1038"),
    ]

    operations = []
