# Generated by Django 2.2.1 on 2019-05-30 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0001_squashed_0021"),
        ("articles", "0011_auto_20190522_1630"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="header_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        )
    ]
