# Generated by Django 2.2.1 on 2019-06-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_article_header_image'),
        ('articles', '0012_article_author'),
    ]

    operations = [
    ]
