# Generated by Django 2.2.1 on 2019-06-04 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0012_auto_20190603_1048"),
        ("articles", "0013_merge_20190603_1229"),
    ]

    operations = []
