# Generated by Django 2.2.1 on 2019-06-04 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20190604_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletopic',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='topics.Topic'),
        ),
    ]
