# Generated by Django 2.2.1 on 2019-06-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_auto_20190612_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='intro',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
    ]
