# Generated by Django 2.2.3 on 2019-07-09 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("articles", "0022_auto_20190624_1622")]

    operations = [
        migrations.AlterModelOptions(
            name="articles", options={"verbose_name_plural": "Articles"}
        )
    ]
