# Generated by Django 2.2.3 on 2019-08-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("articles", "0025_auto_20190716_1346")]

    operations = [
        migrations.AddField(
            model_name="articles",
            name="description",
            field=models.TextField(
                blank=True, default="", max_length=250, verbose_name="Description"
            ),
        )
    ]
