# Generated by Django 2.2.3 on 2019-07-31 11:09

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [("articles", "0025_auto_20190716_1346")]

    operations = [
        migrations.AddField(
            model_name="article",
            name="authors",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "author",
                        wagtail.core.blocks.PageChooserBlock(
                            page_type=["people.Person"]
                        ),
                    ),
                    (
                        "external_author",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("title", wagtail.core.blocks.CharBlock(label="Name")),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "url",
                                    wagtail.core.blocks.URLBlock(
                                        label="URL", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
        migrations.DeleteModel(name="ArticleAuthor"),
    ]
