# Generated by Django 2.2.3 on 2019-08-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_auto_20190731_1109'),
        ('articles', '0026_articles_description'),
    ]

    operations = [
    ]
