# Generated by Django 2.2.4 on 2019-08-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0027_merge_20190802_1535"),
        ("articles", "0027_article_related_links_mdn"),
    ]

    operations = []
