# Generated by Django 2.2.4 on 2019-08-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_auto_20190813_1302'),
        ('articles', '0029_auto_20190813_1435'),
    ]

    operations = [
    ]
