# Generated by Django 2.2.4 on 2019-09-30 09:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0031_auto_20190819_1304'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('published_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='articles',
            managers=[
                ('published_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
