# Generated by Django 2.2.6 on 2019-11-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0034_external_person_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Posts', 'verbose_name_plural': 'Posts'},
        ),
    ]
