# Generated by Django 2.2.1 on 2019-05-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("people", "0002_people")]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="person",
            name="facebook",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="person",
            name="github",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="person",
            name="linkedin",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="person",
            name="twitter",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
    ]
