# Generated by Django 2.2.1 on 2019-06-04 10:50

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [("topics", "0003_subtopic"), ("people", "0005_person_is_mozillian")]

    operations = [
        migrations.RemoveField(model_name="person", name="labels"),
        migrations.AddField(
            model_name="person",
            name="topics",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                related_name="_person_topics_+",
                to="topics.Topic",
                verbose_name="Topics interested in",
            ),
        ),
    ]
