# Generated by Django 2.2.1 on 2019-06-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20190626_0848'),
        ('people', '0009_auto_20190626_1353'),
    ]

    operations = [
    ]
