# Generated by Django 2.2.1 on 2019-06-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0010_auto_20190625_1258"),
        ("people", "0009_auto_20190626_0848"),
    ]

    operations = []
