# Generated by Django 2.2.1 on 2019-06-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0010_merge_20190627_1318"),
        ("people", "0011_merge_20190627_1428"),
    ]

    operations = []
