# Generated by Django 2.2.1 on 2019-07-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_auto_20190702_1059'),
        ('people', '0012_merge_20190628_1108'),
    ]

    operations = [
    ]
