# Generated by Django 2.2.1 on 2019-07-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0013_merge_20190702_1247"),
        ("people", "0013_merge_20190702_1300"),
    ]

    operations = []
