# Generated by Django 2.2.3 on 2019-07-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_merge_20190702_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
    ]
