# Generated by Django 2.2.3 on 2019-07-09 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("people", "0014_merge_20190702_1619")]

    operations = [
        migrations.AlterModelOptions(
            name="people", options={"verbose_name_plural": "People"}
        )
    ]
