# Generated by Django 2.2.3 on 2019-07-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_auto_20190711_1915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedPerson',
        ),
    ]
