# Generated by Django 2.2.3 on 2019-08-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0022_person_websites"),
        ("people", "0022_people_description"),
    ]

    operations = []
