# Generated by Django 2.2.4 on 2019-08-13 15:03

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [("people", "0024_auto_20190813_1302")]

    operations = [
        migrations.AlterField(
            model_name="people",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional short text description, max. 400 characters",
                max_length=400,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="description",
            field=wagtail.core.fields.RichTextField(
                blank=True,
                default="",
                help_text="Optional ‘About me’ section content, supports rich text",
                verbose_name="About",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="websites",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "website",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("url", wagtail.core.blocks.URLBlock(label="URL")),
                                (
                                    "title",
                                    wagtail.core.blocks.CharBlock(required=False),
                                ),
                                (
                                    "icon",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Optional links to any other personal websites",
                null=True,
            ),
        ),
    ]
