# Generated by Django 2.2.4 on 2019-09-30 09:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0028_auto_20190926_1049'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='people',
            managers=[
                ('published_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='person',
            managers=[
                ('published_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
