# Generated by Django 2.2.12 on 2020-05-07 13:52

"""Copy any image set as `Person.image` to populate the `Person.card_image` field
instead, including updating the latest revision of the page (draft or live)"""

from django.db import migrations

from developerportal.apps.common.migration_utils import (
    move_Page_image_to_Page_card_image,
)


def forwards(apps, schema_editor):
    PageSubclass = apps.get_model("people", "Person")
    move_Page_image_to_Page_card_image(PageSubclass)


class Migration(migrations.Migration):

    dependencies = [("people", "0034_people_nav_description")]

    operations = [migrations.RunPython(forwards, migrations.RunPython.noop)]
