# Generated by Django 2.2.14 on 2020-07-06 11:15

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0037_auto_20200511_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2, verbose_name='Country or Region'),
        ),
    ]
