# Generated by Django 2.2.1 on 2019-05-30 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('topic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='topics.Topic')),
            ],
            options={
                'abstract': False,
            },
            bases=('topics.topic',),
        ),
    ]
