# Generated by Django 2.2.1 on 2019-06-10 14:13

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [("topics", "0004_topicfeaturedarticle")]

    operations = [
        migrations.AlterModelOptions(
            name="subtopic",
            options={"verbose_name": "Sub-topic", "verbose_name_plural": "Sub-topics"},
        ),
        migrations.AddField(
            model_name="topic",
            name="intro",
            field=wagtail.core.fields.RichTextField(default=""),
        ),
    ]
