# Generated by Django 2.2.1 on 2019-06-11 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("topics", "0006_auto_20190611_1453")]

    operations = [
        migrations.RenameField(
            model_name="topicperson", old_name="author", new_name="person"
        )
    ]
