# Generated by Django 2.2.1 on 2019-06-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0008_auto_20190612_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='color',
            field=models.CharField(choices=[('blue', 'Blue'), ('orange', 'Orange'), ('green', 'Green'), ('red', 'Red')], default='blue', max_length=14),
        ),
    ]
