# Generated by Django 2.2.1 on 2019-06-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0010_auto_20190618_0840"),
        ("topics", "0012_auto_20190614_1319"),
    ]

    operations = []
