# Generated by Django 2.2.1 on 2019-06-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0012_auto_20190614_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='icon',
            field=models.FileField(default='', upload_to='topics/icons'),
        ),
    ]
