# Generated by Django 2.2.1 on 2019-06-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0010_auto_20190618_0840"),
        ("topics", "0013_topic_icon"),
    ]

    operations = []
