# Generated by Django 2.2.1 on 2019-06-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0013_merge_20190618_1635'),
        ('topics', '0014_merge_20190618_1609'),
    ]

    operations = [
    ]
