# Generated by Django 2.2.1 on 2019-06-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0014_merge_20190618_1609"),
        ("topics", "0013_merge_20190618_1635"),
    ]

    operations = []
