# Generated by Django 2.2.1 on 2019-06-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0015_merge_20190621_1009'),
        ('topics', '0016_auto_20190619_1506'),
    ]

    operations = [
    ]
