# Generated by Django 2.2.1 on 2019-06-24 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0016_auto_20190619_1437"),
        ("topics", "0015_merge_20190621_1009"),
    ]

    operations = []
