# Generated by Django 2.2.1 on 2019-06-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0017_merge_20190624_0904'),
        ('topics', '0017_merge_20190621_1033'),
    ]

    operations = [
    ]
