# Generated by Django 2.2.1 on 2019-06-25 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0018_merge_20190624_1252"),
        ("topics", "0018_merge_20190624_1248"),
    ]

    operations = []
