# Generated by Django 2.2.1 on 2019-07-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0023_auto_20190702_1318"),
        ("topics", "0020_topic_featured"),
    ]

    operations = []
