# Generated by Django 2.2.3 on 2019-07-04 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0025_auto_20190702_1620"),
        ("topics", "0021_auto_20190702_1402"),
    ]

    operations = []
