# Generated by Django 2.2.3 on 2019-07-10 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0027_auto_20190710_1339'),
        ('topics', '0027_auto_20190709_0928'),
    ]

    operations = [
    ]
