# Generated by Django 2.2.3 on 2019-07-11 19:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('mozimages', '0001_initial'),
        ('topics', '0028_merge_20190710_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='intro',
            new_name='description',
        ),
        migrations.AddField(
            model_name='topic',
            name='card_description',
            field=models.TextField(blank=True, default='', max_length=140, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='topic',
            name='card_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mozimages.MozImage', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='topic',
            name='card_title',
            field=models.CharField(blank=True, default='', max_length=140, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='TopicTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='topics.Topic')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics_topictag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='keywords',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='topics.TopicTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
