# Generated by Django 2.2.3 on 2019-07-12 13:37

from django.db import migrations
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('topics', '0030_auto_20190711_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='parent_topics',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='child_topics', to='topics.Topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='get_started',
            field=wagtail.core.fields.StreamField([('panel', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.TextBlock()), ('button_text', wagtail.core.blocks.CharBlock()), ('page_link', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_link', wagtail.core.blocks.URLBlock(help_text='External URL to link to instead of a page.', required=False))]))], blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SubTopic',
        ),
    ]
