# Generated by Django 2.2.3 on 2019-07-16 13:46

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('topics', '0031_auto_20190715_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicsTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='topics.Topics')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics_topicstag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='topics',
            name='keywords',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='topics.TopicsTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
