# Generated by Django 2.2.3 on 2019-07-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0032_auto_20190716_1346'),
        ('topics', '0031_auto_20190717_1258'),
    ]

    operations = [
    ]
