# Generated by Django 2.2.6 on 2019-10-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0045_add_social_image_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='tabbed_panels_title',
        ),
    ]
