# Generated by Django 2.2.7 on 2019-11-07 13:19

import developerportal.apps.topics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("topics", "0047_rephrase_articles_as_posts")]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="icon",
            field=models.FileField(
                blank=True,
                default="",
                help_text="MUST be a black-on-transparent SVG icon ONLY, with no bitmap embedded in it.",
                upload_to="topics/icons",
                validators=[developerportal.apps.topics.models.check_for_svg_file],
            ),
        )
    ]
