# Generated by Django 2.2.11 on 2020-03-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0048_add_svg_help_text_to_topic_icon_filefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='nav_description',
            field=models.TextField(blank=True, default='', max_length=400, verbose_name='Navigation description'),
        ),
    ]
