# Generated by Django 2.2.9 on 2019-12-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0048_add_svg_help_text_to_topic_icon_filefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='show_in_list_views',
            field=models.BooleanField(default=True, help_text='Whether this Topic will be shown in any listing of Topics', verbose_name='show in list views'),
        ),
    ]
