# Generated by Django 2.2.12 on 2020-05-27 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0053_update_streamblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='color',
        ),
    ]
