# Generated by Django 2.2.14 on 2020-07-03 13:05

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0054_remove_topic_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='relevant_events',
            field=wagtail.core.fields.StreamField([('event', wagtail.core.blocks.PageChooserBlock(page_type=['events.Event', 'externalcontent.ExternalEvent']))], blank=True, help_text='Optional space for featured Events, max. 4.', null=True),
        ),
    ]
