# Generated by Django 2.2.4 on 2019-08-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_merge_20190813_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional short text description, max. 400 characters', max_length=400),
        ),
    ]
