# Generated by Django 2.2.9 on 2020-01-16 17:03

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_add_social_image_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='related_links_mdn',
        ),
        migrations.AddField(
            model_name='video',
            name='related_links',
            field=wagtail.core.fields.StreamField([('link', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Name')), ('url', wagtail.core.blocks.URLBlock())]))], blank=True, help_text='Optional links further reading', null=True, verbose_name='Related links'),
        ),
    ]
