# Generated by Django 2.2.12 on 2020-05-07 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_copy_image_to_card_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='image',
        ),
    ]
